// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Tienda.Distribucion.Infraestructura.Persistence;

namespace Tienda.WebApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20201010195658_InitialDbStructure")]
    partial class InitialDbStructure
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Tienda.Distribucion.Domain.Model.Disitribucion.OrdenEntrega", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Estado")
                        .HasColumnName("estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaAnulacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaConsolidacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaFinalizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("ordenEntregaId");

                    b.ToTable("OrdenEntregas");
                });

            modelBuilder.Entity("Tienda.Distribucion.Domain.Model.Disitribucion.OrdenEntrega", b =>
                {
                    b.OwnsOne("Tienda.Distribucion.Domain.ValueObjects.LatitudGps", "LatitudDestino", b1 =>
                        {
                            b1.Property<Guid>("OrdenEntregaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Value")
                                .HasColumnName("latitud")
                                .HasColumnType("decimal(18,12)");

                            b1.HasKey("OrdenEntregaId");

                            b1.ToTable("OrdenEntregas");

                            b1.WithOwner()
                                .HasForeignKey("OrdenEntregaId");
                        });

                    b.OwnsOne("Tienda.Distribucion.Domain.ValueObjects.LongitudGps", "LongitudDestino", b1 =>
                        {
                            b1.Property<Guid>("OrdenEntregaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Value")
                                .HasColumnName("longitud")
                                .HasColumnType("decimal(18,12)");

                            b1.HasKey("OrdenEntregaId");

                            b1.ToTable("OrdenEntregas");

                            b1.WithOwner()
                                .HasForeignKey("OrdenEntregaId");
                        });

                    b.OwnsOne("Tienda.SharedKernel.ValueObjects.PersonNameValue", "NombreCliente", b1 =>
                        {
                            b1.Property<Guid>("OrdenEntregaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnName("nombreCliente")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("OrdenEntregaId");

                            b1.ToTable("OrdenEntregas");

                            b1.WithOwner()
                                .HasForeignKey("OrdenEntregaId");
                        });

                    b.OwnsOne("Tienda.SharedKernel.ValueObjects.PhoneNumber.PhoneNumberValue", "Telefono", b1 =>
                        {
                            b1.Property<Guid>("OrdenEntregaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnName("telefono")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("OrdenEntregaId");

                            b1.ToTable("OrdenEntregas");

                            b1.WithOwner()
                                .HasForeignKey("OrdenEntregaId");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
